config/routes.rb
Rails.application.routes.draw do

  get 'posts/show'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: [:show, :index, :active_friends] do #put get_gravatar_email_hash in the resources if it's going to be used
    member do
      get "active_friends" => "users#active_friends"
    end
  end

  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :posts, only: [:create, :edit, :update, :destroy, :like, :unlike, :activity] do
    member do
      put "like" => "posts#upvote" # Update record
      put "unlike" => "posts#upvote" # Update record
      get "activity" => "posts#get_activity_from_post", as: "activity"
    end
  end

  resources :activities, only: [:index]

  resources :conversations, only: [:create, :show] do
    resources :messages, only: [:create]
  end

  root 'pages#home'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  # Belongs to both a sender and a recipient, both which are a User
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  # If a conversation is deleted, delete all of it's messages
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  # Help retrieve all conversations of the currently logged in user
  scope :involving, -> (user) do
    where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
  end

  # Help check if a conversation exists between any given two users before the conversation is created
  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # Do not let show inherit from application.html.erb
  layout false

  def create
    # Does a conversation exist between two users?
    @conversation =
      if Conversation.between(params[:sender_id],params[:recipient_id]).present?
        # If it does, then find it and return it's id
        Conversation.between(params[:sender_id],params[:recipient_id]).first
      else
        # If not, then simply create a new one
        Conversation.create!(conversation_params)
      end
    p @conversation
      # Return a json response with the id of the conversation
    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = who_am_i(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def who_am_i(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="panel panel-info chat-window">
      <div class="panel-heading chatboxhead">
        <%= fa_icon "commenting-o" %>Chat with <%= @reciever.username %>
        <div class="btn-group pull-right chat-actions">
          <%= link_to "#", class: "toggleChatBox", "data-cid" => @conversation.id do %>
            <%= fa_icon "minus" %>
          <% end %>
          &nbsp;&nbsp;
          <%= link_to "#", class: "closeChat", "data-cid" => @conversation.id do %>
            <%= fa_icon "times" %>
          <% end %>
        </div>
      </div>
        <div class="panel-body chatboxcontent">
          <ul class="chat">
            <% if @messages.any? %>
              <%= render @messages %>
            <% end %>
          </ul>
        </div>
        <div class="panel-footer chatboxinput">
          <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
          <div class="row">
            <div class="col-md-10">
              <%= f.text_area :body, id: "btn-input", class: "chatboxtextarea form-control input-sm", placeholder: "Type your message here...", "data-cid" => @conversation.id %>
            </div>
            <div class="col-md-2 paddingl0">
              <span class="input-group-btn">
                <button class="btn btn-info btn-md" id="btn-chat">
                  Send
                </button>
              </span>
            </div>
          </div>
          <% end %>
        </div>
    </div>
  </div>
</div>
<%= subscribe_to conversation_path(@conversation) %>