config/routes.rb
Rails.application.routes.draw do

  get 'posts/show'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: [:show, :index, :active_friends] do #put get_gravatar_email_hash in the resources if it's going to be used
    member do
      get "active_friends" => "users#active_friends"
    end
  end

  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :posts, only: [:create, :edit, :update, :destroy, :like, :unlike, :activity] do
    member do
      put "like" => "posts#upvote" # Update record
      put "unlike" => "posts#upvote" # Update record
      get "activity" => "posts#get_activity_from_post", as: "activity"
    end
  end

  resources :activities, only: [:index]

  resources :conversations, only: [:create, :show] do
    resources :messages, only: [:create]
  end

  root 'pages#home'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codeline", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Timeline", activities_path %></li>
          <li>
            <%= link_to users_path do %>
              People
              <% unless request_count.zero? %>
                <span class="badge"><%= request_count %></span>
              <% end %>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_tag current_user.email, size: 20 %><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user.username) %></li>
              <li><%= link_to "Friends", users_path(people: "friends") %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_no_sidebar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeline</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <!-- Any view using the this layout (no side-bar) EXCEPT the root path, should have a padding-top to make content visible below the navbar -->
  <body style="<%= current_page?(root_path) ? nil : 'padding-top: 50px;' %>">
    <%= render 'layouts/header' %>
    <div id="main">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12 reset">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>
<div class="row-offcanvas row-offcanvas-left">
  <div id="sidebar" class="sidebar-offcanvas">
      <div class="col-md-12">
        <h3><%= gravatar_tag current_user.email, size: 80 %><%= current_user.username %></h3>
        <hr>
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><a href="#">Timeline</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">Friends</a></li>
          <li><a href="#">Messages</a></li>
          <li><a href="#">Code Snippets</a></li>
          <li><a href="#">Gallery</a></li>
        </ul>
      </div>
  </div>
<% end %>
<!-- The end part of the row-offcanvas div is in application.html.erb -->

app/views/layouts/_sidenav.html.erb
<div class="row-offcanvas row-offcanvas-left">
  <div id="sidebar" class="sidebar-offcanvas">
      <div class="col-md-12">
        <% if current_user %>
          <h3><%= gravatar_tag current_user.email, size: 80 %><%= current_user.username %></h3>
        <% end %>
        <hr>
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><a href="#">Timeline</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">Friends</a></li>
          <li><a href="#">Messages</a></li>
          <li><a href="#">Code Snippets</a></li>
          <li><a href="#">Gallery</a></li>
        </ul>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codeline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 50px;">
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidenav' %>
      <div id="main">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12 reset">
              <%= link_to "#", class: "toggle-sidebar", "data-toggle" => "offcanvas" do %>
                <%= fa_icon "navicon" %>
              <% end %>
              <%# bootstrap_flash class: "text-center" %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- End sidebar -->
</body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codeline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body class="authentication-layout">
  <div class="container">
    <%= bootstrap_flash class: "text-center" %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/devise.html.erb
<%= render 'layouts/no_sidebar' %>

app/views/layouts/root.html.erb
<%= render 'layouts/no_sidebar' %>